# Generated by Django 5.0.3 on 2024-03-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtsection',
            name='closeTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='courtsection',
            name='openTime',
            field=models.TimeField(null=True),
        ),
    ]
