# Generated by Django 5.0.3 on 2024-03-16 06:20

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_clientid_admin_adminid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('dealer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_info', models.CharField(max_length=100)),
                ('marginOfProfit', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='inventorysports',
            name='typeChoices',
            field=models.CharField(choices=[('basketball', 'basketball'), ('football', 'footvall'), ('tennis', 'tennis')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='adminId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='adminId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.admin'),
        ),
        migrations.AlterField(
            model_name='court',
            name='courtId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courtsection',
            name='courtSectionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courtsection',
            name='sectionType',
            field=models.CharField(choices=[('basketball', 'basketball'), ('football', 'football'), ('tennis', 'tennis')], max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='foodId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='vendingMachineId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.vendingmachine'),
        ),
        migrations.AlterField(
            model_name='foodpurchase',
            name='foodId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.food'),
        ),
        migrations.AlterField(
            model_name='foodpurchase',
            name='purchaseId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='foodpurchase',
            name='reservationId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.reservation'),
        ),
        migrations.AlterField(
            model_name='inventoryrent',
            name='inventoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.inventorysports'),
        ),
        migrations.AlterField(
            model_name='inventoryrent',
            name='inventoryRentId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventoryrent',
            name='reservationId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.reservation'),
        ),
        migrations.AlterField(
            model_name='inventorysports',
            name='inventoryId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='clientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='courtsectionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.courtsection'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservationID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendingmachine',
            name='vendingMachineId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='food',
            name='dealer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.dealer'),
        ),
    ]
