# Generated by Django 5.0.3 on 2024-03-22 17:14

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_courtsection_closetime_courtsection_opentime'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
