# Generated by Django 5.0.3 on 2024-05-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reservation',
            new_name='reservationId',
        ),
    ]
