# Generated by Django 5.0.3 on 2024-05-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_reservation_review_reservationid'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtsection',
            name='pricePerHour',
            field=models.IntegerField(null=True),
        ),
    ]
